version: '3'
services:
  listener:
    build: ./listener
    privileged: true
    network_mode: host
    entrypoint: 'bin/start.sh'
  prometheus:
    env_file: .env
    image: prom/prometheus
    network_mode: host
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
    user: '1000'
    restart: always
    ports:
      - 9090:9090

  grafana:
    env_file: .env
    image: grafana/grafana
    network_mode: host
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/server.crt:/etc/grafana/server.crt
      - ./grafana/server.key:/etc/grafana/server.key
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/dashboards
      - ./grafana/data:/var/lib/grafana
    user: '1000'
    restart: always
    ports:
      - 443:3000
