global:
  scrape_interval: 5s

scrape_configs:
  - job_name: Prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: Ruuvi
    static_configs:
      - targets: ['172.17.0.1:3010']
  # Add other services here
