{
 "title": "All ruuvitags",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "location", "query": "label_values(location)" }
  ]
 },
 "panels": [
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruuvi_battery", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Outside temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ruuvi_temperature{location='outside'})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "expr": "ruuvi_temperature{location=~'$location'}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ruuvi_humidity{location=~'$location'}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ruuvi_pressure{location=~'$location'}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}