{
 "title": "Identify tags",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Highest temperature deviation in unknown tags",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sort_desc(stddev_over_time(ruuvi_temperature{room=''}[15m]))",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Closest unknown tags",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sort_desc(ruuvi_rssi{room=''})", "legendFormat": "{{id}} {{room}}" }
   ]
  },
  {
   "title": "Closest known tags",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(ruuvi_rssi{room!=''})",
     "legendFormat": "{{id}} ({{room}})"
    }
   ]
  }
 ]
}