{
 "title": "Käppyrät by room",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "room_type", "query": "label_values(room_type)" },
   { "name": "shortid_length", "query": "3" }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "expr": "avg by (room) (\n  label_replace((\n    ruuvi_temperature{room_type=~'$room_type'}\n   ), 'shortid', \"$1\", 'id', '([a-z0-9]{$shortid_length}).*'\n  )\n)",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (room) (\n  label_replace((\n    ruuvi_humidity{room_type=~'$room_type'}\n   ), 'shortid', \"$1\", 'id', '([a-z0-9]{$shortid_length}).*'\n  )\n)",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (room) (\n  label_replace(ruuvi_pressure{room_type=~'$room_type'}, 'shortid', \"$1\", 'id', '([a-z0-9]{$shortid_length}).*')\n)",
     "legendFormat": "{{room}}"
    }
   ]
  }
 ]
}