{
 "title": "Keskiarvot by room",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "room_type", "query": "label_values(room_type)" },
   { "name": "shortid_length", "query": "3" },
   {
    "name": "window",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "expr": "avg by (room) (\n  label_replace((\n    avg_over_time(ruuvi_temperature{room_type=~'$room_type'}[$window])\n    + avg_over_time(ruuvi_temperature_calibration{room_type=~'$room_type'}[$window])\n   ), 'shortid', \"$1\", 'id', '([a-z0-9]{$shortid_length}).*'\n  )\n)",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (room) (\n  label_replace((\n    avg_over_time(ruuvi_humidity{room_type=~'$room_type'}[$window])\n    * avg_over_time(ruuvi_humidity_calibration{room_type=~'$room_type'}[$window])\n   ), 'shortid', \"$1\", 'id', '([a-z0-9]{$shortid_length}).*'\n  )\n)",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (room) (\n  label_replace((\n    avg_over_time(ruuvi_pressure{room_type=~'$room_type'}[$window])\n    + avg_over_time(ruuvi_pressure_calibration{room_type=~'$room_type'}[$window])\n   ), 'shortid', \"$1\", 'id', '([a-z0-9]{$shortid_length}).*'\n  )\n)",
     "legendFormat": "{{room}}"
    }
   ]
  }
 ]
}